[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CrystOD"
version = "0.2.1"
authors = [
  {name = "Yasuhide Mochizuki"},
  {email = "mochizuki@rs.tus.ac.jp"},
]
description = "Python-based command line tools calculating irreducible representations (irreps) of Symmetry-Adapted Linear Combination (SALC) for Crystal Orbital Diagram (CrystOD), and phonon irreps."
readme = "README.md"
license = {text = "GNU General Public License v3 (GPLv3)"}
requires-python = ">=3.9"
dependencies = [
  "phonopy",
  "spglib",
  "spgrep",
  "irrep",
  "irreptables",
  "ase",
  "numpy",
  "pandas",
  "openpyxl",
  "sympy",
]

[project.scripts]
crystod = "crystod.cli:main"

[tool.setuptools]
packages = ["crystod"]

[project.urls]
Homepage = "https://mochizuki-tus.github.io/"
