ATOM_NAME = Sr Ti O
DIM = 4 4 4
BAND = 0 0 0    0 0.500 0    0.500 0.500 0    0 0 0    0.500 0.500 0.500    0 0.500 0, 0.500 0.500 0    0.500 0.500 0.500
BAND_LABELS = GM X M GM R X  M R
FORCE_SETS = READ
#FORCE_CONSTANTS = READ
BAND_CONNECTION = .TRUE.
#
