"""The MCP server: one ``MCPServer`` with the ten CrystOD tools registered.

``create_server()`` builds the server (tests connect to it in-process with
``mcp.client.Client``); ``main()`` is the ``crystod-mcp`` console script and
``python -m crystod_mcp``, which serve it over stdio.
"""

from __future__ import annotations

import argparse
import inspect

from mcp.server.mcpserver import MCPServer

from . import __version__
from .tools import TOOLS

SERVER_NAME = "crystod-mcp"

INSTRUCTIONS = """\
CrystOD symmetry analyses for crystals and molecules, as tools.

Inputs are plain text: space groups as international symbols (Pm-3m,
P6_3/mmc) or numbers (221); point groups as Hermann-Mauguin symbols (m-3m,
3m, -43m); irrep labels in ISO-IR notation (R4+, GM5-, X3-: k-point name,
index, parity sign); k points as labels (GM, X, M, R) or three fractional
coordinates in the primitive reciprocal basis ("1/2 1/2 1/2"); crystal
structures as the full text of a VASP POSCAR; molecules as the full text of
an XYZ file; phonon force data as the full text of a phonopy FORCE_SETS with
the supercell dimension it was computed for.

Results are Markdown; every result ends with the citation that applies to
it (ISO-IR for the irrep labels, CrystOD for the analysis). A failed call
returns one sentence naming the problem and the remedy.
"""


def create_server() -> MCPServer:
    """Build the server with the ten tools registered in spec order.

    The tool description is the cleaned docstring (``inspect.getdoc``), so
    the first paragraph a model reads is the tool's own summary; the input
    schema is generated by the SDK from the type annotations. Results are
    plain text (``structured_output=False``).
    """
    server = MCPServer(SERVER_NAME, instructions=INSTRUCTIONS, version=__version__)
    for tool in TOOLS:
        server.add_tool(tool, description=inspect.getdoc(tool), structured_output=False)
    return server


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="crystod-mcp",
        description=(
            "Model Context Protocol server for CrystOD (stdio transport). "
            "Register it with your MCP client, e.g. "
            "`claude mcp add crystod -- crystod-mcp`; the per-call time limit "
            "is CRYSTOD_MCP_TIMEOUT seconds (default 60)."
        ),
    )
    parser.add_argument(
        "--version", action="version", version=f"crystod-mcp {__version__}"
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    """Console-script entry point: serve over stdio until the client hangs up."""
    build_parser().parse_args(argv)
    create_server().run(transport="stdio")


if __name__ == "__main__":
    main()
